name: BuildWheels

on: [pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.1
        env:
          # TODO build for more
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.10, <3.12"
          CIBW_SKIP: "*musllinux*"

          CIBW_BEFORE_ALL_LINUX: "bash {project}/scripts/prepare_golang.sh"
          CIBW_BEFORE_BUILD: "rm -rfv {project}/build"
          CIBW_ENVIRONMENT: PATH=$PATH:/usr/local/go/bin

          CIBW_TEST_REQUIRES: pytest pytest_asyncio
          CIBW_TEST_COMMAND: "pytest {project}/tests"
        with:
          package-dir: .
          output-dir: wheelhouse
          config-file: "./pyproject.toml"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
