name: BuildWheels

on: [pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.1
        env:
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: "pytest"
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.10"
          CIBW_BEFORE_ALL: >
            curl -LO https://go.dev/dl/go1.21.1.linux-amd64.tar.gza && \
            tar -C /usr/local -xzf go1.21.1.linux-amd64.tar.gz && \
            export PATH=$PATH:/usr/local/go/bin && \
            go version
        with:
          package-dir: .
          output-dir: wheelhouse
          config-file: "./pyproject.toml"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
