name: BuildWheels

on: [pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.1
        env:
          CIBW_TEST_REQUIRES: pytest pytest_asyncio
          CIBW_TEST_COMMAND: "pytest {project}/tests"
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.10"
        with:
          package-dir: .
          output-dir: wheelhouse
          config-file: "./pyproject.toml"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
