name: Lint

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    name: flake8 & black
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: codespell-project/actions-codespell@master
        with:
          ignore_words_list: fo,ists,oll,optin,ot,smove,tre,whe,EXAT,exat
          skip: ./tests/pprof_data/*

      - uses: actions/setup-python@v4
        with:
          python-version: 3.10
          architecture: "x64"

      - name: Cache venv
        uses: actions/cache@v2
        with:
          path: venv
          # Look to see if there is a cache hit for the corresponding requirements file
          key: lintenv-v2

      - name: Install Dependencies
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -U pip flake8 black

      - name: Flake8 test
        run: |
          . venv/bin/activate
          flake8 .

      - name: Black test
        run: |
          . venv/bin/activate
          black --check .
