name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: Pytest
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]
        # python: ["3.7", "3.8", "3.9", "3.10", "3.11.1"]
        python: ["3.10", "3.11"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          architecture: "x64"
      - name: Cache venv
        uses: actions/cache@v2
        with:
          path: venv
          # Look to see if there is a cache hit for the corresponding requirements file
          key:
            poetryenv-${{ matrix.os }}-${{ matrix.python }}-${{
            hashFiles('poetry.lock') }}
      - name: Install Dependencies
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -U pip setuptools
          pip install poetry
          poetry install
          python -c "import sys; print(sys.version)"
          pip list
      - name: Pytest
        env:
          REDIS_VERSION: ${{ matrix.redis }}
        run: |
          . venv/bin/activate
          pytest
